# Netlify Build Configuration for AI Caption Generator Frontend

[build]
  # Build command for the frontend
  command = "cd frontend && npm install && npm run build"
  
  # Directory with the built files
  publish = "frontend/dist"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Frontend environment variables
  VITE_API_BASE_URL = "https://your-backend.railway.app"

# Redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin","editor"], Country = ["US"]}

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optimize images
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Form handling (if needed for contact forms)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
